<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('countryName' => 'Algeria','country_code' => 'DZ','dialCode' => '213','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Angola','country_code' => 'AO','dialCode' => '244','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Ascension Island','country_code' => '','dialCode' => '247','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Benin','country_code' => 'BJ','dialCode' => '229','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Botswana','country_code' => 'BW','dialCode' => '267','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'British Indian Ocean Territory','country_code' => '','dialCode' => '0','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Burkina Faso','country_code' => 'BF','dialCode' => '226','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Burundi','country_code' => 'BI','dialCode' => '257','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Cameroon','country_code' => 'CM','dialCode' => '237','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Cape Verde','country_code' => 'CV','dialCode' => '238','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Central African Republic','country_code' => 'CF','dialCode' => '236','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Chad','country_code' => 'TD','dialCode' => '235','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Comoros','country_code' => 'KM','dialCode' => '269','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Congo Brazzaville','country_code' => 'CG','dialCode' => '242','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Congo, DRC','country_code' => 'CD','dialCode' => '243','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Cote d\'Ivoire','country_code' => 'CI','dialCode' => '225','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Djibouti','country_code' => 'DJ','dialCode' => '253','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Egypt','country_code' => 'EG','dialCode' => '20','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Equatorial Guinea','country_code' => 'GQ','dialCode' => '240','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Eritrea','country_code' => 'ER','dialCode' => '291','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Ethiopia','country_code' => 'ET','dialCode' => '251','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Gabon','country_code' => 'GA','dialCode' => '241','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Gambia','country_code' => 'GM','dialCode' => '220','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Ghana','country_code' => 'GH','dialCode' => '233','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Guinea','country_code' => 'GN','dialCode' => '224','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Guinea-Bissau','country_code' => 'GW','dialCode' => '245','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Kenya','country_code' => 'KE','dialCode' => '254','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Lesotho','country_code' => 'LS','dialCode' => '266','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Liberia','country_code' => 'LR','dialCode' => '231','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Libya','country_code' => 'LY','dialCode' => '218','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Madagascar','country_code' => 'MG','dialCode' => '261','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Malawi','country_code' => 'MW','dialCode' => '265','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Mali','country_code' => 'ML','dialCode' => '223','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Mauritania','country_code' => 'MR','dialCode' => '222','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Mauritius','country_code' => 'MU','dialCode' => '230','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Mayotte','country_code' => 'YT','dialCode' => '262','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Morocco','country_code' => 'MA','dialCode' => '212','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Mozambique','country_code' => 'MZ','dialCode' => '258','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Namibia','country_code' => 'NA','dialCode' => '264','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Niger','country_code' => 'NE','dialCode' => '227','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Nigeria','country_code' => 'NG','dialCode' => '234','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Reunion','country_code' => 'RE','dialCode' => '262','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Rwanda','country_code' => 'RW','dialCode' => '250','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Saint Helena','country_code' => 'SH','dialCode' => '290','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Sao Tome and Principe','country_code' => 'ST','dialCode' => '239','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Senegal','country_code' => 'SN','dialCode' => '221','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Seychelles','country_code' => 'SC','dialCode' => '248','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Sierra Leone','country_code' => 'SL','dialCode' => '232','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Somalia','country_code' => 'SO','dialCode' => '252','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'South Africa','country_code' => 'ZA','dialCode' => '27','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Sudan','country_code' => 'SD','dialCode' => '249','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Swaziland','country_code' => 'SZ','dialCode' => '268','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Tanzania','country_code' => 'TZ','dialCode' => '255','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Togo','country_code' => 'TG','dialCode' => '228','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Tunisia','country_code' => 'TN','dialCode' => '216','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Uganda','country_code' => 'UG','dialCode' => '256','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Western Sahara','country_code' => 'EH','dialCode' => '0','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Zambia','country_code' => 'ZM','dialCode' => '260','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Zimbabwe','country_code' => 'ZW','dialCode' => '263','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'South Sudan','country_code' => 'SDG','dialCode' => '233','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Kenya-DEV','country_code' => 'KE-DEV','dialCode' => '254','region_code' => 'af','continent' => 'Africa'),
            array('countryName' => 'Antarctica','country_code' => '','dialCode' => '0','region_code' => 'an','continent' => 'Antarctica'),
            array('countryName' => 'Bouvet Island','country_code' => '','dialCode' => '0','region_code' => 'an','continent' => 'Antarctica'),
            array('countryName' => 'French Southern Territories','country_code' => '','dialCode' => '596','region_code' => 'an','continent' => 'Antarctica'),
            array('countryName' => 'Afghanistan','country_code' => 'AF','dialCode' => '93','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Armenia','country_code' => 'AM','dialCode' => '374','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Bahrain','country_code' => 'BH','dialCode' => '973','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Bangladesh','country_code' => 'BD','dialCode' => '880','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Bhutan','country_code' => 'BT','dialCode' => '975','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Brunei Darussalam','country_code' => 'BN','dialCode' => '673','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Cambodia','country_code' => 'KH','dialCode' => '855','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'China (PRC)','country_code' => 'CN','dialCode' => '86','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Cyprus','country_code' => 'CY','dialCode' => '357','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Hong Kong','country_code' => 'HK','dialCode' => '852','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'India','country_code' => 'IN','dialCode' => '91','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Indonesia','country_code' => 'ID','dialCode' => '62','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Iran','country_code' => 'IR','dialCode' => '98','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Iraq','country_code' => 'IQ','dialCode' => '964','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Israel','country_code' => 'IL','dialCode' => '972','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Japan','country_code' => 'JP','dialCode' => '81','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Kazakhstan','country_code' => 'KZ','dialCode' => '76','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Korea, North','country_code' => 'KP','dialCode' => '850','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Korea, South','country_code' => 'KR','dialCode' => '82','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Kuwait','country_code' => 'KW','dialCode' => '965','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Kyrgyzstan','country_code' => 'KG','dialCode' => '996','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Laos','country_code' => 'LA','dialCode' => '856','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Lebanon','country_code' => 'LB','dialCode' => '961','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Macau','country_code' => 'MO','dialCode' => '853','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Malaysia','country_code' => 'MY','dialCode' => '60','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Maldives','country_code' => 'MV','dialCode' => '960','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Mongolia','country_code' => 'MN','dialCode' => '976','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Myanmar','country_code' => 'MM','dialCode' => '95','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Nepal','country_code' => 'NP','dialCode' => '977','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Oman','country_code' => 'OM','dialCode' => '968','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Pakistan','country_code' => 'PK','dialCode' => '92','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Palestinian Territory','country_code' => 'PS','dialCode' => '970','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Philippines','country_code' => 'PH','dialCode' => '63','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Qatar','country_code' => 'QA','dialCode' => '974','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Saudia Arabia','country_code' => 'SA','dialCode' => '966','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Singapore','country_code' => 'SG','dialCode' => '65','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Sri Lanka','country_code' => 'LK','dialCode' => '94','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Syria','country_code' => 'SY','dialCode' => '963','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Taiwan','country_code' => 'TW','dialCode' => '886','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Tajikistan','country_code' => 'TJ','dialCode' => '992','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Thailand','country_code' => 'TH','dialCode' => '66','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Turkey','country_code' => 'TR','dialCode' => '90','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Turkmenistan','country_code' => 'TM','dialCode' => '993','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'United Arab Emirates','country_code' => 'AE','dialCode' => '971','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Uzbekistan','country_code' => 'UZ','dialCode' => '998','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Vietnam','country_code' => 'VN','dialCode' => '84','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'Yemen','country_code' => 'YE','dialCode' => '967','region_code' => 'as','continent' => 'Asia'),
            array('countryName' => 'American Samoa','country_code' => 'AS','dialCode' => '1684','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Australia','country_code' => 'AU','dialCode' => '61','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Christmas Island','country_code' => '','dialCode' => '618','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Cocos (Keeling) Island','country_code' => '','dialCode' => '61','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Cook Islands','country_code' => 'CK','dialCode' => '682','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Fiji','country_code' => 'FJ','dialCode' => '679','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'French Polynesia','country_code' => 'PF','dialCode' => '689','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Guam','country_code' => 'GU','dialCode' => '1671','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Heard and McDonald Islands','country_code' => '','dialCode' => '0','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Kiribati','country_code' => 'KI','dialCode' => '686','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Marshall Islands','country_code' => 'MH','dialCode' => '692','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Micronesia','country_code' => 'FM','dialCode' => '691','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Nauru','country_code' => 'NR','dialCode' => '674','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'New Caledonia','country_code' => 'NC','dialCode' => '687','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'New Zealand','country_code' => 'NZ','dialCode' => '64','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Niue','country_code' => 'NU','dialCode' => '683','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Norfolk Island','country_code' => 'NF','dialCode' => '672','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Northern Mariana Islands','country_code' => 'MP','dialCode' => '1670','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Palau','country_code' => 'PW','dialCode' => '680','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Papua New Guinea','country_code' => 'PG','dialCode' => '675','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Pitcairn Island','country_code' => 'PN','dialCode' => '0','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Samoa','country_code' => 'WS','dialCode' => '685','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Solomon Islands','country_code' => 'SB','dialCode' => '677','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Timor-Leste','country_code' => 'TL','dialCode' => '670','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Tokelau','country_code' => '','dialCode' => '690','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Tonga','country_code' => 'TO','dialCode' => '676','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Tuvalu','country_code' => 'TV','dialCode' => '688','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Vanuatu','country_code' => 'VU','dialCode' => '678','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Wallis and Futuna','country_code' => 'WF','dialCode' => '681','region_code' => 'ao','continent' => 'Oceania'),
            array('countryName' => 'Aland','country_code' => 'AX','dialCode' => '0','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Albania','country_code' => 'AL','dialCode' => '355','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Andorra','country_code' => 'AD','dialCode' => '376','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Austria','country_code' => 'AT','dialCode' => '43','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Azerbaijan','country_code' => 'AZ','dialCode' => '994','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Belarus','country_code' => 'BY','dialCode' => '375','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Belgium','country_code' => 'BE','dialCode' => '32','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Bosnia and Herzegovina','country_code' => 'BA','dialCode' => '387','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Bulgaria','country_code' => 'BG','dialCode' => '359','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Croatia','country_code' => 'HR','dialCode' => '385','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Czech Republic','country_code' => 'CZ','dialCode' => '420','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Denmark','country_code' => 'DK','dialCode' => '45','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Estonia','country_code' => 'EE','dialCode' => '372','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Faroe Islands','country_code' => 'FO','dialCode' => '298','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Finland','country_code' => 'FI','dialCode' => '358','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'France','country_code' => 'FR','dialCode' => '33','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Georgia','country_code' => 'GE','dialCode' => '995','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Germany','country_code' => 'DE','dialCode' => '49','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Gibraltar','country_code' => 'GI','dialCode' => '350','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Greece','country_code' => 'GR','dialCode' => '30','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Guernsey','country_code' => 'GG','dialCode' => '0','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Hungary','country_code' => 'HU','dialCode' => '36','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Iceland','country_code' => 'IS','dialCode' => '354','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Ireland','country_code' => 'IE','dialCode' => '353','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Isle of Man','country_code' => 'IM','dialCode' => '0','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Italy','country_code' => 'IT','dialCode' => '39','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Jersey','country_code' => 'JE','dialCode' => '0','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Latvia','country_code' => 'LV','dialCode' => '371','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Liechtenstein','country_code' => 'LI','dialCode' => '423','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Lithuania','country_code' => 'LT','dialCode' => '370','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Luxembourg','country_code' => 'LU','dialCode' => '352','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Macedonia','country_code' => 'MK','dialCode' => '389','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Malta','country_code' => 'MT','dialCode' => '356','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Moldova','country_code' => 'MD','dialCode' => '373','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Monaco','country_code' => 'MC','dialCode' => '377','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Montenegro','country_code' => '','dialCode' => '382','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Netherlands','country_code' => 'NL','dialCode' => '31','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Norway','country_code' => 'NO','dialCode' => '47','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Poland','country_code' => 'PL','dialCode' => '48','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Portugal','country_code' => 'PT','dialCode' => '351','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Romania','country_code' => 'RO','dialCode' => '40','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Russia','country_code' => 'RU','dialCode' => '7','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'San Marino','country_code' => 'SM','dialCode' => '378','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Serbia','country_code' => 'CS','dialCode' => '381','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Slovakia','country_code' => 'SK','dialCode' => '421','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Slovenia','country_code' => 'SI','dialCode' => '386','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Spain','country_code' => 'ES','dialCode' => '34','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Svalbard and Jan Mayen Islands','country_code' => 'SJ','dialCode' => '0','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Sweden','country_code' => 'SE','dialCode' => '46','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Switzerland','country_code' => 'CH','dialCode' => '41','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Ukraine','country_code' => 'UA','dialCode' => '380','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'United Kingdom','country_code' => 'GB','dialCode' => '44','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Vatican City','country_code' => 'VA','dialCode' => '379','region_code' => 'eu','continent' => 'Europe'),
            array('countryName' => 'Anguilla','country_code' => 'AI','dialCode' => '1264','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Antigua and Barbuda','country_code' => 'AG','dialCode' => '1268','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Bahamas','country_code' => 'BS','dialCode' => '1242','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Barbados','country_code' => 'BB','dialCode' => '1246','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Belize','country_code' => 'BZ','dialCode' => '501','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Bermuda','country_code' => 'BM','dialCode' => '1441','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'British Virgin Islands','country_code' => 'IO','dialCode' => '1284','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Canada','country_code' => 'CA','dialCode' => '1','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Cayman Islands','country_code' => 'KY','dialCode' => '1345','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Costa Rica','country_code' => 'CR','dialCode' => '506','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Cuba','country_code' => 'CU','dialCode' => '53','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Dominica','country_code' => 'DM','dialCode' => '1767','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Dominican Republic','country_code' => 'DO','dialCode' => '1809','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'El Salvador','country_code' => 'SV','dialCode' => '503','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Georgia and Sanwich Islands','country_code' => '','dialCode' => '0','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Greenland','country_code' => 'GL','dialCode' => '299','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Grenada','country_code' => 'GD','dialCode' => '1473','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Guadeloupe','country_code' => 'GP','dialCode' => '590','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Guatemala','country_code' => 'GT','dialCode' => '502','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Haiti','country_code' => 'HT','dialCode' => '509','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Honduras','country_code' => 'HN','dialCode' => '504','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Jamaica','country_code' => 'JM','dialCode' => '1876','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Jordan','country_code' => 'JO','dialCode' => '962','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Martinique','country_code' => 'MQ','dialCode' => '596','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Mexico','country_code' => 'MX','dialCode' => '52','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Montserrat','country_code' => 'MS','dialCode' => '1664','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Nicaragua','country_code' => 'NI','dialCode' => '505','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Panama','country_code' => 'PA','dialCode' => '507','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Puerto Rico','country_code' => 'PR','dialCode' => '1787','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Saint Kitts and Nevis','country_code' => 'KN','dialCode' => '1869','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Saint Lucia','country_code' => 'LC','dialCode' => '1758','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Saint Pierre and Miquelon','country_code' => 'PM','dialCode' => '508','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Saint Vincent and the Grenadin','country_code' => 'VC','dialCode' => '1784','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Suriname','country_code' => 'SR','dialCode' => '597','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Turks and Caicos','country_code' => 'TC','dialCode' => '1649','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'United States of America','country_code' => 'US','dialCode' => '1','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'United States Virgin Islands','country_code' => 'VI','dialCode' => '1340','region_code' => 'na','continent' => 'North America'),
            array('countryName' => 'Argentina','country_code' => 'AR','dialCode' => '54','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Aruba','country_code' => 'AW','dialCode' => '297','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Bolivia','country_code' => 'BO','dialCode' => '591','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Brazil','country_code' => 'BR','dialCode' => '55','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Chile','country_code' => 'CL','dialCode' => '56','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Colombia','country_code' => 'CO','dialCode' => '57','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Ecuador','country_code' => 'EC','dialCode' => '593','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Falkland Islands (Malvinas)','country_code' => 'FK','dialCode' => '500','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'French Guiana','country_code' => 'GF','dialCode' => '594','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Guyana','country_code' => 'GY','dialCode' => '592','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Netherlands Antilles','country_code' => 'AN','dialCode' => '599','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Paraguay','country_code' => 'PY','dialCode' => '595','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Peru','country_code' => 'PE','dialCode' => '51','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Saint Barthelemy','country_code' => 'BL','dialCode' => '0','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Saint Martin','country_code' => 'MF','dialCode' => '0','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Trinidad and Tobago','country_code' => 'TT','dialCode' => '1868','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Uruguay','country_code' => 'UY','dialCode' => '598','region_code' => 'sa','continent' => 'South America'),
            array('countryName' => 'Venezuela','country_code' => 'VE','dialCode' => '58','region_code' => 'sa','continent' => 'South America')
        );

        foreach ($countries as $country) {
            \App\Models\Countries\Countries::create([
                'country_name' => $country['countryName'],
                'country_code' => $country['country_code'],
                'country_extension' => $country['dialCode'],
                'region_code' => $country['region_code'],
                'continent' => $country['continent']
            ]);
        }
    }
}
